# Generated by Django 5.1.3 on 2024-11-28 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False, help_text='Indicates whether the habit was completed on this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='base.habit')),
            ],
            options={
                'verbose_name_plural': 'Habit Completions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['habit', 'date', 'status'], name='base_habitc_habit_i_6c3db6_idx')],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
